//! Login autostart for the hotkey agent — the Windows counterpart of the
//! systemd user services used on Linux.
//!
//! The `Run` value points at a one-line `.vbs` shim rather than at `dictate.exe`
//! directly: `wscript` can start a console program with the window hidden, so
//! logging in does not flash a terminal.

use crate::control::Slot;
use anyhow::{bail, Context, Result};
use std::path::PathBuf;
use std::process::{Command, Stdio};

const RUN_KEY: &str = r"HKCU\Software\Microsoft\Windows\CurrentVersion\Run";
const VALUE_NAME: &str = "Dictate";
const LAUNCHER: &str = "hotkey-agent.vbs";

fn dictate_dir() -> PathBuf {
    dirs::config_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join("dictate")
}

fn launcher_path() -> PathBuf {
    dictate_dir().join(LAUNCHER)
}

fn run_value() -> String {
    format!("wscript.exe //B \"{}\"", launcher_path().display())
}

fn reg(args: &[&str]) -> Result<bool> {
    let status = Command::new("reg.exe")
        .args(args)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .context("failed to run reg.exe")?;
    Ok(status.success())
}

fn write_launcher() -> Result<PathBuf> {
    let exe = std::env::current_exe().context("could not resolve the dictate executable")?;
    let dir = dictate_dir();
    std::fs::create_dir_all(&dir)?;
    let path = launcher_path();
    // VBScript escapes a quote by doubling it.
    let command = format!("\"\"{}\"\" hotkeys --warm", exe.display());
    std::fs::write(
        &path,
        format!(
            "' Generated by `dictate autostart install`. Starts the dictate hotkey\n\
             ' agent with no console window. Delete via `dictate autostart remove`.\n\
             CreateObject(\"WScript.Shell\").Run \"{command}\", 0, False\n"
        ),
    )?;
    Ok(path)
}

/// Launch the hotkey agent now, detached and windowless.
pub fn start_agent() -> Result<()> {
    let launcher = launcher_path();
    if !launcher.exists() {
        write_launcher()?;
    }
    Command::new("wscript.exe")
        .arg("//B")
        .arg(&launcher)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .context("failed to start the hotkey agent")?;
    Ok(())
}

/// Ask a running hotkey agent to exit. Returns false when none was listening.
pub fn stop_agent() -> Result<bool> {
    crate::control::send(Slot::Hotkeys, "shutdown")
}

/// True when a hotkey agent is currently listening.
pub fn agent_running() -> bool {
    crate::control::send(Slot::Hotkeys, "ping").unwrap_or(false)
}

/// True when the login entry is present.
pub fn installed() -> bool {
    reg(&["query", RUN_KEY, "/v", VALUE_NAME]).unwrap_or(false)
}

pub fn install() -> Result<()> {
    let launcher = write_launcher()?;
    if !reg(&[
        "add",
        RUN_KEY,
        "/v",
        VALUE_NAME,
        "/t",
        "REG_SZ",
        "/d",
        &run_value(),
        "/f",
    ])? {
        bail!("failed to write the {VALUE_NAME} value under {RUN_KEY}");
    }

    let _ = stop_agent();
    std::thread::sleep(std::time::Duration::from_millis(300));
    start_agent()?;

    println!("Dictate hotkey agent installed:");
    println!("  Launcher: {}", launcher.display());
    println!("  Startup:  {RUN_KEY}\\{VALUE_NAME}");
    println!("It registers your shortcuts at login and keeps warm daemons ready.");
    Ok(())
}

pub fn remove() -> Result<()> {
    let _ = stop_agent();
    let _ = reg(&["delete", RUN_KEY, "/v", VALUE_NAME, "/f"]);
    let launcher = launcher_path();
    if launcher.exists() {
        std::fs::remove_file(&launcher)?;
    }
    println!("Dictate hotkey agent removed from startup.");
    Ok(())
}

pub fn print_status() {
    let installed = installed();
    let running = agent_running();
    let marker = if running {
        "✓"
    } else if installed {
        "!"
    } else {
        "✗"
    };
    let state = if running {
        "running"
    } else if installed {
        "installed but not running"
    } else {
        "not installed"
    };
    println!("Dictate hotkey agent: {marker} {state}");
    if !running {
        println!("  Run: dictate autostart install");
    }
}
